### PR TITLE
Threads for FDM

### PR DESCRIPTION
**Pull request by koendv**
Hi.

I'm using your threadlib, and would like to contribute a small part.

I've created a set of threads, to be printed using FDM, and then cleaned up using taps and dies. 
Could you take a look and give me your opinion?

regards,

Koenraad

### CODE REVIEW

**Comment by adrianschlatter** [comment]
Hi Koenraad

I have realized - late, I know - that you opened and closed a PR several months ago. Moreover, I realize that you have the skills to understand and extend the build system :) I understand that metric-FDM thread is your own design optimised for printing, right? This keeps me from reopening the PR as I prefer threadlib to remain focused on standardized threads.

Best regards,
Adrian

**Comment by koendv** [comment]
Yes. You can discard the ticket if you wish, but I'd like to give some background.

FDM is widely used, but if upward slopes are more than 45 degrees you need to print supports, and (manually) remove the support after printing. There is no limit to downward slopes. So my idea was designing a screw thread where upward slopes are at most 45 degrees. There is a setting in slicer called "flower vase" which might be useful. https://slic3r.org/blog/tip-printing-vases/
I think there is a place for a thread which is perhaps not 100% according to ISO, but if you can print both screw and nut it will be used. Choosing parameters right there might even be some compatibility between the two: a 3d-printed screw printed with a 45 degree angle might be used with a metal screw with the 60 degree ISO angle. 

Thank you for making your library public.

regards,

koen









On Oct 29, 2019, at 8:41 PM, Adrian Schlatter <notifications@github.com> wrote:

> Hi Koenraad
> 
> I have realized - late, I know - that you opened and closed a PR several months ago. Moreover, I realize that you have the skills to understand and extend the build system :) I understand that metric-FDM thread is your own design optimised for printing, right? This keeps me from reopening the PR as I prefer threadlib to remain focused on standardized threads.
> 
> Best regards,
> Adrian
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
https://slic3r.org/blog/tip-printing-vases/

**Comment by koendv** [comment]
> a 3d-printed screw printed with a 45 degree angle might be used with a metal screw with the 60 degree ISO angle. 

Ugh. Should have been: a 3d-printed screw printed with a 45 degree angle might be used with a metal *nut* with the 60 degree ISO angle.

**Comment by adrianschlatter** [comment]
Hi Koenraad

Thanks for providing that insight. I wasn’t aware of that incompatibility but your statement regarding printability makes sense. And you cannot print the screw sideways to reduce the overhang to 30° because you would get even worse overhangs along the crests.

A norm for FDM-printable threads would be a nice thing. I assume you have tried to find one?

Best regards, Adrian

**Comment by koendv** [comment]
There is ISO/TC 261, which is developing standards for 3D-printing. But I am not aware of any (proposed) standards for screw threads.

If, as a hobbyist, you need a metric thread on a 3d-printed workpiece, I would buy threaded brass inserts, like these: https://www.amazon.de/Aerzetix-Messing-Eins%C3%A4tze-Duroplast-Gewinde-7-4mm-C19143/dp/B075XHV3GH/
These are available from M1 up to M10 (and in imperial). These are machined parts, which you push in with a hot soldering iron.

If, as a hobbyist, you wish to 3D-print a screw, I think choosing 45 degrees is the wisest choice. An example is this: https://www.thingiverse.com/thing:193647
The demo is an 8x25 hex bolt. In the Nut_Job.scad OpenScad source file I find:

//Outer diameter of the thread
thread_outer_diameter           = 8;		
//Thread step or Pitch (2mm works well for most applications ref. ISO262: M3=0.5,M4=0.7,M5=0.8,M6=1,M8=1.25,M10=1.5)
thread_step    					= 2;
//Step shape degrees (45 degrees is optimised for most printers ref. ISO262: 30 degrees)
step_shape_degrees 				= 45;	
//Length of the threaded section
thread_length  					= 25;	

This gives an idea of what is realistic in FDM. 

regards,

koen

**Pull request closed without merging**
